package io.commercestacksolutions.priceproviderservice.facade.organization.mapper;

import io.commercestacksolutions.commons.mapper.AbstractMapper;
import io.commercestacksolutions.commons.mapper.RestRequestMappingContext;
import io.commercestacksolutions.commons.mapper.exception.DataMappingException;
import io.commercestacksolutions.priceproviderservice.commons.messagekeys.MessageKeys;
import io.commercestacksolutions.priceproviderservice.dataaccess.group.entity.GroupEntity;
import io.commercestacksolutions.priceproviderservice.dataaccess.group.GroupEntityRepository;
import io.commercestacksolutions.priceproviderservice.dataaccess.organization.entity.OrganizationEntity;
import io.commercestacksolutions.priceproviderservice.dataaccess.organization.definitions.OrganizationType;
import io.commercestacksolutions.priceproviderservice.facade.organization.restentity.OrganizationRestEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

@Component
public class OrganizationEntityMapper extends AbstractMapper<OrganizationRestEntity, OrganizationEntity, RestRequestMappingContext<String>> {

    @Autowired
    private GroupEntityRepository groupEntityRepository;

    @Override
    public OrganizationEntity createTarget() {
        return new OrganizationEntity();
    }

    @Override
    public void convert(OrganizationRestEntity source, OrganizationEntity target, RestRequestMappingContext<String> context) throws DataMappingException {
        // Set String id from context (null for create – auto-generated by @PrePersist)
        if (context.getId() != null) {
            target.setId(context.getId());
        }
        // Set path from the REST entity
        if (source.getPath() != null) {
            target.setPath(source.getPath());
        }
        target.setName(source.getName());
        target.setOrganizationType(source.getOrganizationType() != null ? new OrganizationType(source.getOrganizationType()) : null);

        // Convert parent paths to entity references (look up by path)
        if (source.getParentRefs() != null) {
            Set<GroupEntity> parentRefs = new HashSet<>();
            for (String parentPath : source.getParentRefs()) {
                GroupEntity parent = groupEntityRepository.findByPath(parentPath).orElseThrow(
                    () -> new DataMappingException(MessageKeys.ERROR_MAPPING_ENTITY_NOT_FOUND,
                        Map.of("path", parentPath, "entityType", "Group")));
                parentRefs.add(parent);
            }
            target.setParentRefs(parentRefs);
        }

        // Convert sub paths to entity references
        // Since 'subRefs' is the inverse side of the bidirectional relationship (mappedBy="parentRefs"),
        // we need to update the 'parentRefs' field of the sub entities to persist the relationship
        if (source.getSubRefs() != null) {
            Set<String> newSubPaths = source.getSubRefs();
            Set<String> currentSubPaths = new HashSet<>();
            
            // Collect current sub paths
            if (target.getSubRefs() != null) {
                for (GroupEntity oldSub : target.getSubRefs()) {
                    if (oldSub.getPath() != null) {
                        currentSubPaths.add(oldSub.getPath());
                    }
                }
            }
            
            // Remove relationships for subs that are no longer in the list
            for (String oldSubPath : currentSubPaths) {
                if (!newSubPaths.contains(oldSubPath)) {
                    GroupEntity oldSub = groupEntityRepository.findByPath(oldSubPath).orElse(null);
                    if (oldSub != null) {
                        // Remove by path to avoid instance comparison issues
                        oldSub.getParentRefs().removeIf(p -> target.getPath() != null && target.getPath().equals(p.getPath()));
                    }
                }
            }
            
            // Add new relationships
            Set<GroupEntity> subRefs = new HashSet<>();
            for (String subPath : newSubPaths) {
                GroupEntity sub = groupEntityRepository.findByPath(subPath).orElseThrow(
                    () -> new DataMappingException(MessageKeys.ERROR_MAPPING_ENTITY_NOT_FOUND,
                        Map.of("path", subPath, "entityType", "Group")));
                subRefs.add(sub);
                // Only add if not already present (check by path, not instance)
                boolean alreadyExists = sub.getParentRefs().stream()
                    .anyMatch(p -> target.getPath() != null && target.getPath().equals(p.getPath()));
                if (!alreadyExists) {
                    sub.getParentRefs().add(target);
                }
            }
            target.setSubRefs(subRefs);
        }
    }
}
